### ISSUE TITLE
housekeeping vagrant files 

### ISSUE THREAD

**Issue by gedw99** [mcandre/tonixxx#101]
I am really happy your doing a proejct like this as i am also, and so will switch to helping you.

Can you add a mage command for managing vagrant ?
Just firstly a way to list whats on disk, so users can see why their Hard Disk is full. 
Its a simple start i know, but finding where vagrant puts them is a pain.

**Comment by mcandre** [comment]
> Can you add a mage command for managing vagrant ?

If you are using `mage` to build your project, then it is likely that your implementation language is Go, in which case, you don't, strictly speaking, need tonixxx, nor Vagrant, in order to quickly and automatically generate application ports! You should probably use [goxcart](https://github.com/mcandre/goxcart) and Docker instead, as these are much more efficient than virtual machines.

I do provide a mage task for goxcart, in [mage-extras](https://github.com/mcandre/mage-extras).

If you are using mage, or make, or whatever to build your project, but not using Go; or if you are using Go but for whatever reason are interested in porting/testing on non-Linux environments, then you probably just want to run `vagrant ssh df -h` or similar command depending on the particular guest OS, to diagnose disk usage issues.
